/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gloomyfish_opencv_plugin_FaceExtraLayer */

#ifndef _Included_com_gloomyfish_opencv_plugin_FaceExtraLayer
#define _Included_com_gloomyfish_opencv_plugin_FaceExtraLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gloomyfish_opencv_plugin_FaceExtraLayer
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_com_gloomyfish_opencv_plugin_FaceExtraLayer_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_gloomyfish_opencv_plugin_FaceExtraLayer
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gloomyfish_opencv_plugin_FaceExtraLayer_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gloomyfish_opencv_plugin_FaceExtraLayer
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gloomyfish_opencv_plugin_FaceExtraLayer_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gloomyfish_opencv_plugin_FaceExtraLayer
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gloomyfish_opencv_plugin_FaceExtraLayer_nativeStop
  (JNIEnv *, jclass, jlong);

  /*
   * Class:     com_gloomyfish_opencv_plugin_FaceExtraLayer
   * Method:    nativeSetFaceSize
   * Signature: (JI)V
   */
  JNIEXPORT void JNICALL Java_com_gloomyfish_opencv_plugin_FaceExtraLayer_nativeSetFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_gloomyfish_opencv_plugin_FaceExtraLayer
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_gloomyfish_opencv_plugin_FaceExtraLayer_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
